### ISSUE TITLE
LocalizationProvider in Viewer localization = undefined

### ISSUE THREAD

**Issue by A-D-E** [react-pdf-viewer/examples#15]
Hi,

I am currently trying to implement the German version. I want to do it with defaultLayout. In react-dev-tools, Component Provider "LocalizationProvider" has correct props, but in "Viewer" "LocalizationProvider" is undefined. 
btw i have translated the local json to german. You are welcome to use it, possibly also as part of the package.

Sandbox: https://codesandbox.io/s/pdf-default-4hr2z

best regards

**Comment by phuoc-ng** [comment]
Hi @A-D-E,

I am sorry for not to reply this question! Usually I don't check the issues in this repos, since it is a place that I collect the example codes only.

Regarding your question, you just pass the `localization` to the `Viewer`.
I updated the sandbox [here](https://codesandbox.io/s/pdf-default-forked-us3ul?file=/src/App.js:1020-1053)

```js
<Viewer
    localization={de_DE}
/>
```

<img width="260" alt="Screen Shot 2021-01-20 at 20 03 33" src="https://user-images.githubusercontent.com/57786711/105178622-dbef2800-5b5a-11eb-8d1d-a634e891b7c2.png">

If you have any questions or suggestions, please add it in the [main repos](https://github.com/react-pdf-viewer/react-pdf-viewer/issues).

**Comment by A-D-E** [comment]
Thanks for your help, it worked!

regards
Andrej


Der Inhalt dieser E-Mail ist vertraulich und ausschließlich für den
bezeichneten Adressaten bestimmt. Wenn Sie nicht der vorgesehene Adressat
dieser E-Mail oder dessen Vertreter sein sollten, so beachten Sie bitte,
dass jede Form der Kenntnisnahme, Veröffentlichung, Vervielfältigung oder
Weitergabe des Inhalts dieser E-Mail unzulässig ist. Wir bitten Sie, sich
in diesem Fall mit dem Absender der E-Mail in Verbindung zu setzen.


This e-mail message including any attachments is for the sole use of the
intended recipient(s) and may contain privileged or confidential
information. Any unauthorized review, use, disclosure or distribution is
prohibited. If you are not the intended recipient, please immediately
contact the sender by reply e-mail and delete the original message and
destroy all copies thereof.
